@startuml Reservation system

title
Reservation system
end title

class ReservationSystem {
    +ReservationSystem()
}

class Seat {

}

class StandardSeat {

}

class VIPSeat {

}

class DisabledSeat {

}

StandardSeat <|-- Seat
VIPSeat <|-- Seat
DisabledSeat <|-- Seat

@enduml
