@startuml Reservation system

title
Reservation system
end title

class Seat {
    +Seat(char symbol, unsigned int id, bool isTaken) noexcept

    +char getSymbol() const noexcept
    +unsigned int getID() const noexcept
    +bool isTaken() const noexcept

    +void take() noexcept
    +void free() noexcept

    #const char symbol_
    #const unsigned int id_
    #bool isTaken_
}

class StandardSeat {
    +StandardSeat(unsigned int id, bool isTaken) noexcept
}

class VIPSeat {
    +VIPSeat(unsigned int id, bool isTaken)
}

class DisabledSeat {
    +DisabledSeat(unsigned int id, bool isTaken)
}

class Person {
    +Person(const std::string& name, const std::string& surname, const std::string& phoneNum, const std::string& email, const std::string& pesel)
    +Person(const std::string& name, const std::string& surname, const std::string& phoneNum, const std::string& email, const std::string& pesel, bool isVaccinated)

    +std::string getName() const
    +std::string getSurname() const
    +std::string getPhoneNum() const
    +std::string getEmail() const
    +std::string getPesel() const

    +unsigned int getAge() const noexcept

    +bool isVaccinated_

    -std::string name_
    -std::string surname_
    -std::string phoneNum_
    -std::string email_
    -std::string pesel_
}

StandardSeat <|-- Seat
VIPSeat <|-- Seat
DisabledSeat <|-- Seat

@enduml
